export const travelPage = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Yaseeni Travel AI — Flight Search</title>
<meta name="description" content="Search flight offers and build a travel plan with Yaseeni Travel AI.">
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,-apple-system,sans-serif;color:#152238;background:#f4f7fb;font-synthesis:none}
*{box-sizing:border-box}body{margin:0}header{background:#10213c;color:white;padding:22px max(20px,calc((100% - 1080px)/2));display:flex;justify-content:space-between;align-items:center;gap:12px;flex-wrap:wrap}
.brand{font-weight:800;font-size:20px;letter-spacing:-.5px}.brand span{color:#83d6bd}header a{color:#fff;text-decoration:none;font-size:14px}
main{max-width:1080px;margin:0 auto;padding:40px 18px}.hero{padding:18px 0 28px}.eyebrow{text-transform:uppercase;letter-spacing:2px;font-size:12px;font-weight:800;color:#137a69}.hero h1{font-size:clamp(32px,5vw,54px);letter-spacing:-1.5px;line-height:1.06;margin:12px 0}.hero p{color:#58687d;max-width:620px;line-height:1.6}
.panel{background:white;border:1px solid #e0e7f0;border-radius:22px;padding:24px;box-shadow:0 14px 45px #172c4610}.formgrid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px}.field{display:flex;flex-direction:column;gap:7px}.field label{font-size:12px;font-weight:750;color:#4c5b70}.field input,.field select{width:100%;border:1px solid #d5deea;border-radius:10px;padding:12px;font:inherit;background:#fff;color:#152238;min-width:0}.span2{grid-column:span 2}.options{display:flex;gap:18px;flex-wrap:wrap;margin:18px 0;color:#526277;font-size:14px}.btn{border:0;border-radius:11px;background:#137a69;color:white;padding:14px 20px;font-weight:800;font-size:15px;cursor:pointer}.btn:disabled{opacity:.6;cursor:wait}.note{font-size:12px;color:#6a788b;line-height:1.55;margin-top:14px}.results{margin-top:22px;display:grid;gap:12px}.result{border:1px solid #e0e7f0;border-radius:14px;padding:16px;background:#fff}.result h3{margin:0 0 8px;font-size:16px}.price{font-size:24px;font-weight:850;color:#137a69}.muted{color:#637188;font-size:13px;line-height:1.55}.link{display:inline-block;margin-top:10px;color:#137a69;font-weight:750}.features{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:24px}.feature{background:#eaf1f7;border-radius:16px;padding:18px}.feature strong{display:block;margin-bottom:7px}.feature p{margin:0;color:#607087;font-size:13px;line-height:1.5}footer{max-width:1080px;margin:auto;padding:0 18px 35px;color:#738095;font-size:12px}
@media(max-width:760px){.formgrid{grid-template-columns:repeat(2,minmax(0,1fr))}.features{grid-template-columns:1fr}.panel{padding:16px}.span2{grid-column:span 2}}@media(max-width:420px){.formgrid{grid-template-columns:1fr}.span2{grid-column:span 1}}
</style></head>
<body>
<header><div class="brand">✈ Yaseeni <span>Travel AI</span></div><a href="#search">Search flights　·　Plan a trip</a></header>
<main>
<section class="hero"><div class="eyebrow">Your AI travel companion</div><h1>Find your next<br>journey.</h1><p>Search available flight offers, compare itinerary details, and open a Google Flights search for current market fares. Start here, then continue your trip on WhatsApp.</p></section>
<section class="panel" id="search"><form id="flightForm">
<div class="formgrid">
<div class="field"><label for="origin">FROM · IATA CODE</label><input id="origin" name="origin" placeholder="AUH" minlength="3" maxlength="3" required value="AUH"></div>
<div class="field"><label for="destination">TO · IATA CODE</label><input id="destination" name="destination" placeholder="CJB" minlength="3" maxlength="3" required value="CJB"></div>
<div class="field"><label for="departureDate">DEPARTURE</label><input id="departureDate" name="departureDate" type="date" required></div>
<div class="field"><label for="returnDate">RETURN (OPTIONAL)</label><input id="returnDate" name="returnDate" type="date"></div>
<div class="field"><label for="adults">ADULTS</label><select id="adults" name="adults"><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7</option><option>8</option><option>9</option></select></div>
<div class="field"><label for="children">CHILDREN</label><select id="children" name="children"><option>0</option><option>1</option><option>2</option><option>3</option><option>4</option><option>5</option><option>6</option><option>7</option><option>8</option></select></div>
<div class="field"><label for="currencyCode">CURRENCY</label><select id="currencyCode" name="currencyCode"><option>AED</option><option>INR</option><option>USD</option><option>EUR</option></select></div>
<div class="field" style="justify-content:end"><button class="btn" id="submitBtn" type="submit">Search flights →</button></div>
</div></form><div class="note">Flight offers depend on the configured provider. Amadeus test mode uses limited sample data and is not a guarantee of live availability. No ticket is booked by this search.</div><div class="results" id="results" aria-live="polite"></div></section>
<section class="features"><div class="feature"><strong>Flight comparison</strong><p>Review returned fares, routes, stopovers and flight details.</p></div><div class="feature"><strong>Google Flights link</strong><p>Open an external search to verify current market prices.</p></div><div class="feature"><strong>WhatsApp AI</strong><p>Ask the travel assistant to help refine dates, passenger needs and itinerary plans.</p></div></section>
</main><footer>Yaseeni Travel AI · Prices and availability may change. Confirm fare rules and passenger details with the booking provider before paying.</footer>
<script>
const form=document.getElementById('flightForm'),out=document.getElementById('results'),btn=document.getElementById('submitBtn');
const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());document.getElementById('departureDate').min=today.toISOString().slice(0,10);
form.addEventListener('submit',async e=>{e.preventDefault();out.replaceChildren();btn.disabled=true;btn.textContent='Searching…';const payload=Object.fromEntries(new FormData(form).entries());payload.origin=payload.origin.trim().toUpperCase();payload.destination=payload.destination.trim().toUpperCase();payload.adults=Number(payload.adults);payload.children=Number(payload.children);
try{const res=await fetch('/api/flights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Search failed');render(data)}catch(err){showMessage(err.message+' — You can still check Google Flights below.')}finally{btn.disabled=false;btn.textContent='Search flights →'}});
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n}
function showMessage(msg){out.append(el('div','result',msg))}
function render(data){if(data.error){showMessage(data.error);return}if(data.message)showMessage(data.message);if(data.offers&&data.offers.length){data.offers.forEach((offer,i)=>{const card=el('article','result');card.append(el('h3','',`Flight option ${i+1} · ${offer.currency||''} ${offer.total||'Price unavailable'}`));(offer.itineraries||[]).forEach((it,j)=>{card.append(el('div','muted',`Journey ${j+1}: ${it.segments.map(s=>`${s.from} ${s.departure||''} → ${s.to} ${s.arrival||''} (${s.airline||s.flightNumber||'Airline'} ${s.flightNumber||''})`).join(' · ')} · Duration ${it.duration||'not supplied'}`))});out.append(card)})}if(data.googleFlightsUrl){const card=el('div','result');card.append(el('h3','','Check current fares on Google Flights'));card.append(el('p','muted','Opens an external search. Confirm the displayed price, baggage and fare rules before booking.'));const a=el('a','link','Open Google Flights ↗');a.href=data.googleFlightsUrl;a.target='_blank';a.rel='noopener noreferrer';card.append(a);out.append(card)}if(!data.offers?.length&&!data.message)showMessage('No offers were returned. Try another date or open Google Flights.')}
</script></body></html>`;
